export const GET_ESTABLISHMENTS_REQUEST = 'GET_ESTABLISHMENTS_REQUEST'
export const GET_ESTABLISHMENTS_SUCCESS = 'GET_ESTABLISHMENTS_SUCCESS'
export const GET_ESTABLISHMENTS_ERROR = 'GET_ESTABLISHMENTS_ERROR'

export const SELECT_ESTABLISHMENT_SCHEDULING = 'SELECT_ESTABLISHMENT_SCHEDULING'